Develop
VitaliyDorofechyk/src pull request #1
Opened 2020-11-25 18:48 UTC by VitaliyDorofechyk

done 6 tasks check!=)

2020-11-25 20:08 UTC, MaksimFalei requested changes

2020-11-25 20:08 UTC, MaksimFalei commented on task/task2/task3.js
> +console.log(arrTask3);
Не совсем, но так даже лучше)

2020-11-25 20:08 UTC, MaksimFalei commented on task/task2/task4.js
> +//Начинает доходить как до утки на 3 сутки))))
Немного не правильно ты понял задание, тут нужно отфильтровать исходный массив, чтобы новый состоял только из элементов, которые больше 10. Используй метод filter для этого

2020-11-25 20:08 UTC, MaksimFalei commented on task/task2/task5.js
> +task5([4, 'hi', 'my', 4, 'friend']);
Тут тоже, результатом выполнения твоей функции должен быть новый массив, т.е. она должна возвращать новый массив. Для решения этой задачи можно использовать перебор исходного и добавление подходяших строк в него с заглавной первой буквой, либо использовать reduce

2020-11-25 20:08 UTC, MaksimFalei commented on task/task2/task6.js
> +
Следи за стилистикой кода

2020-11-25 20:08 UTC, MaksimFalei commented on task/task2/task6.js
> +    do { let num = parseFloat(prompt('я посчитаю любую сумму чисел которую ты введешь, чтоб узнать ответ введи 15', 2));
let  с новой строки должен быть. Всегда после фыгурные скобки должны быть последними на строке

2020-11-25 20:08 UTC, MaksimFalei commented on task/task2/task6.js
> +    if ( num == 15) {
Должна быть ещё одна табудяция, следи за отступами

2020-11-25 20:08 UTC, MaksimFalei commented on task/task2/task6.js
> +        arr6.push(`${num}`);
Зачем ты число пушишь в массив как строку?

2020-11-25 20:08 UTC, MaksimFalei commented on task/task2/task6.js
> +    else if ( typeof num == 'number') {
Ещё должна быть проверка на isNaN

2020-11-25 20:12 UTC, VitaliyDorofechyk commented on task/task2/task3.js
> +console.log(arrTask3);
спасибо=)

2020-11-25 20:19 UTC, VitaliyDorofechyk commented on task/task2/task6.js
> +        arr6.push(`${num}`);
как ты научил так и делаю)))

2020-11-26 16:45 UTC, MaksimFalei commented on task/task2/task6.js
> +        arr6.push(`${num}`);
чёт я такого не припомню)

2020-11-28 17:30 UTC, closed without merging